---
title: "R-Ladies Melbourne Events"
output:
  github_document:
linkcolor: magenta
urlcolor: magenta
---

```{r echo=FALSE,message=FALSE,fig.width=5,fig.height=5,fig.align='center',cache=TRUE}
library(png)
library(grid)
img <- readPNG("logo.png")
grid.raster(img)
```

\clearpage

# Events in 2019

## [Gold star reproducibility: straightforward containerisation with open-source tools](https://github.com/R-LadiesMelbourne/2019-09-17-Gold-star-reproducibility-containerisation)

Prepared and presented by Saras Windecker


## [Introduction to R workshop](https://github.com/R-LadiesMelbourne/2019-08-17_Introduction-to-R-workshop)

Prepared and presented by [Goknur Giner](https://twitter.com/goknurginer) and [Nikki Rubinstein](https://twitter.com/nikkirubinstein)

## [Cluster analysis with international education data – challenges and insights](https://github.com/R-LadiesMelbourne/2019-07-15-Cluster-analysis-with-international-education-data)

Prepared and presented by [Jenny Shen](https://www.nousgroup.com/people/jenny-shen/)


## [NLP with SpaCy in R](https://github.com/R-LadiesMelbourne/2019-06-18-NLP-with-SpaCy-in-R)

Prepared and presented by [Ana Mamatelashvili](https://github.com/anamamatelashvili)


## [Baby one more time - reproducibility in R and when to bring in the big guns](https://mrslaviniag.github.io/xaringan_presentations/rladies_presentation_22_May_2019.html#1)

Prepared and presented by [Lavinia Gordon](https://www.linkedin.com/in/lavinia-gordon-74b58659/?originalSubdomain=au)

## [Producing publication-ready documents in R Markdown](https://github.com/R-LadiesMelbourne/2019-02-27-publications-ready-documents-with-Rmarkdown)

Prepared and presented by:

* [Soroor Zadeh](https://github.com/soroorh), Master Student in Statistics at the University of Melbourne and Research Assisant at the Walter and Eliza Hall Institute of Medical Research 

* [Anna Quaglieri](https://github.com/annaquaglieri16), PhD Student in Bioinformatics at the University of Melbourne and the Walter and Eliza Hall Institute of Medical Research 


# Events in 2018

## [Semiparametric and non parametric models in R](https://github.com/R-LadiesMelbourne/2018-12-06-Semiparametric-and-non-parametric-models-in-R)

Prepared and presented by [Soroor Zadeh](https://github.com/soroorh), Master Student in Statistics at the University of Melbourne and Research Assisant at the Walter and Eliza Hall Institute of Medical Research.

## [From zero to science hero in 1 week](https://github.com/R-LadiesMelbourne/2018-11-14_From-zero-to-data-science-hero-in-1-week)

Speaker: [Fiona Milne](https://twitter.com/fionascottym), data scientist at Eliiza, a ML/AI consulting company.


## [How R you? - R-Ladies Melbourne second anniversary](https://github.com/R-LadiesMelbourne/2018-10-16_How-R-You)

Organised by [Anna Quaglieri](https://github.com/annaquaglieri16), [Saskia Freytag](https://twitter.com/trashystats) and [Göknur Giner](https://twitter.com/goknurginer).

Find introduction slides [here](https://docs.google.com/presentation/d/1WKIw9l4LfMaf3eY7KTHDCqlV0wHLfXB9NdcR68JGpNE/edit?usp=sharing).

Go to [How R you - R-Ladies Melbourne Tips website](https://rladies-melbourne-tips.netlify.com/).

## [R as a tool for complex systems modelling](https://github.com/R-LadiesMelbourne/2018-09-19-R-as-a-tool-for-complex-systems-modelling)

Run by [Caitlin Adams](https://www.linkedin.com/in/caitlinisabeladams/?originalSubdomain=au), PhD Student at Swinburne University's Centre for Astrophysics and Supercomputing.


## [Getting down and up with blogging with R!](https://github.com/R-LadiesMelbourne/2018-08-28-Getting-down-and-up-with-blogging-with-R)

Run by [Emi Tanaka](https://emitanaka.github.io/), Lecturer in Statistics, University of Sydney
  
## [Follow me! Introduction to social media analysis in R](https://github.com/R-LadiesMelbourne/Follow-Me-Introduction-to-social-media-analysis-in-R)

Run by:

  1. [Maria Prokofieva](https://www.vu.edu.au/contact-us/maria-prokofieva), Senior Lecturer, College of Business, Victoria University
  2. [Anna Quaglieri](https://github.com/annaquaglieri16), PhD Student in Bioinformatics, The Walter and Eliza Hall Institute
  3. [Saskia Freytag](https://github.com/SaskiaFreytag), Postdoctoral Fellow, The Walter and Eliza Hall Institute


## [Introduction to R](https://github.com/R-LadiesMelbourne/2018-06-16_Introduction-to-R-workshop)

Run by:

  1. [Roxane Legaie](https://twitter.com/RoxaneLegaie), Lead Clinical Bioinformatician at Peter MacCallum Cancer Centre.
  2. [Adele Barugahare](https://www.monash.edu/researchinfrastructure/bioinformatics/about/people), Bioinformatician at Monash University.

## [Everything you need to know to create your R package!](https://github.com/earowang/rladies-pkg)

Find all the R code [here](https://github.com/earowang/romato).

Prepared and presented by [Earo Wang](https://earo.me/).

## [More than words - Text analysis in R](https://github.com/R-LadiesMelbourne/2018-04-17_Text_Aanalysis_in_R)

Prepared and presented by [Maria Prokofieva](https://www.vu.edu.au/contact-us/maria-prokofieva)
Find video of the seminar on YouTube https://www.youtube.com/watch?v=WOVwOQ5XhTI.

## [Parallel Programming in R](https://github.com/R-LadiesMelbourne/2018-03-15_Parallelprogramming_in_R)

Prepared and presented by [Soroor Zadeh](https://github.com/soroorh)
Find video of the seminar on YouTube https://www.youtube.com/watch?v=sXEn4M6YDOA.


## [Public Transport Maps and Geospatial Data In R](https://github.com/R-LadiesMelbourne/2018-02-12_PublicTransportMaps_and_GeospatialDataInR)

Speaker [Belinda Maher](https://twitter.com/mingabelle). 
Find video of the seminar on YouTube https://www.youtube.com/watch?v=84G6ZNTEHCo 


# Events in 2016-2017

## [Launch Meetup](https://github.com/R-LadiesMelbourne/2016-10-18-Launch-Meetup) 

Speaker: [Di Cook](https://monash.edu/research/explore/en/persons/dianne-cook(be6154be-91fd-4bed-bf30-d1da98e88212).html), Professor of Business Analytics in the Department of Econometrics and Business Statistics at Monash University.

## [R Notebooks and Interactive Graphics](https://github.com/R-LadiesMelbourne/2017-02-20-RNotebooksAheatmapInteractiveGraphics)

Speakers:

  1. [Natalia Da Silva](http://ndasilva.public.iastate.edu/), PhD in Statistics from Iowa State University
  2. [Jovana Maksimovic](https://www.mcri.edu.au/users/dr-jovana-maksimovic), Postdoctoral scientist in Bioinformatics at the Murdoch Children Research Institute.

## [Git and GitHub workshop](https://github.com/R-LadiesMelbourne/2017-04-05-Git-Workshop)

Speaker: [Soroor Zadeh](https://twitter.com/SoroorHediyeh?lang=en), Research Assistant in Bioinformatics at the Walter and Eliza Hall Institute.

## [Twitter Workshop](https://github.com/R-LadiesMelbourne/2017-05-22-Twitter-Workshop)

Speaker: [Anna Quaglieri](https://github.com/annaquaglieri16), PhD candidate in Bioinformatics at the Walter and Eliza Hall Institute.

Helper: [Saskia Freitag](https://twitter.com/trashystats), Postdoctoral scientist in Bioinformatics at the Walter and Eliza Hall Institute.

## [Web Scraping & Sports Analytics](https://github.com/R-LadiesMelbourne/2017-06-15-Web-ScrapingAndSportsAnalytics)

Speaker: [Stephanie Kovalchik](http://on-the-t.com/), Tennis Data Scientist at the Game Insight Group at Tennis Australia and researcher at the Institute of Sport Exercise and Active Living at Victoria University.

## [Build Neural Network with R](https://github.com/R-LadiesMelbourne/2017-07-17-BuildNeuralNetwork)

Speaker: [Kristen Hunter](https://statistics.fas.harvard.edu/people/kristen-hunter), PhD candidate in statistics at Harvard University.

## [mixOmics: Combine Large Scale Datasets](https://github.com/R-LadiesMelbourne/2017-08-22-combine-large-scale-dataset-workshop)

Find materials on how to use the mixOmics package, an R package to combine large scale genomics datasets.

Speaker: [Kim-Anh Le Cao](https://findanexpert.unimelb.edu.au/display/person791255), Academic, Mathematics and Statistics at the University of Melbourne.

Find video of workshop on YouTube:
- Part 1. Introduction to mixOmics https://www.youtube.com/watch?v=ZnIFeguzNA4&t=34s
- Part 2. Hands on turorial on mixOmics https://www.youtube.com/watch?v=C8ReqvpdSI0

## [Introduction to R Workshop](https://github.com/R-LadiesMelbourne/2017-09-23-Introduction_to_R_workshop)

Speakers:

  1. [Roxane Legaie](https://twitter.com/RoxaneLegaie), Lead Clinical Bioinformatician at Peter MacCallum Cancer Centre.
  2. [Nikki Rubinstein](https://twitter.com/nikkirubinstein), PhD candidate at Melbourne University.

## [Random Forest, Climate Change and Food Production](https://github.com/R-LadiesMelbourne/2017-10-25-ClimateChange_and_RandomForest)

Speaker: [Elizabeth Vogel](https://twitter.com/evbln), PhD researcher at the Australian-German Climate & Energy College, University of Melbourne, focusing on climate extreme events and agriculture.

Find video of seminar on YouTube at https://www.youtube.com/watch?v=4rjhPGa4ef0&t=2s. 

## [One Year of R-Ladies Melbourne](https://github.com/R-LadiesMelbourne/2017-10-25_OneYearOfRLadiesMelbourne)

Prepared by [Anna Quaglieri](https://github.com/annaquaglieri16) and [Marie Trussart](https://www.researchgate.net/profile/Marie_Trussart) and presented by [Marie Trussart](https://www.researchgate.net/profile/Marie_Trussart).

## [Introduction to R-Shiny](https://github.com/R-LadiesMelbourne/2017-11-23-Introduction-To-RShiny)

Prepared and presented by [Soroor Zadeh](https://github.com/soroorh) and [Marie Trussart](https://www.researchgate.net/profile/Marie_Trussart).

## [Christmas Party](https://github.com/R-LadiesMelbourne/2017-12-14_Christmas-Party)

Organised and directed by [Saskia Freytag](https://github.com/SaskiaFreytag)



